apps/events/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import NationalEventSearchTemplateView, SearchEventsAPIListView, MyEventsAPIListView, MyEventsTemplateView, CreateNewEventFormView, \
    CreateNewEventCreateAPIView, EventDetailView, ListEventThreadsAPIView, SendMessageToEventThreadAPIView, \
    ListParticipantsAPIView, ListInvitedAPIView, DeleteEventAPIView, UpdateEventFormView, UpdateEventAPIView, \
    StartNewEventThreadCreateAPIView, InviteUserAPIView, ParticipateInEventAPIView, CancelParticipationInEventAPIView

urlpatterns = [
    url(r'api/search/national$', login_required(SearchEventsAPIListView.as_view()), name="api-events-national-search"),  # GET
    url(r'api/mine$', login_required(MyEventsAPIListView.as_view()), name="api-events-mine-list"),  # GET
    url(r'api/new$', login_required(CreateNewEventCreateAPIView.as_view()), name="api-events-create"),  # POST
    url(r'api/event/(?P<pk>[0-9]+)/threads$', login_required(ListEventThreadsAPIView.as_view()), name='api-events-threads-list'),  # GET
    url(r'api/event/(?P<pk>[0-9]+)/threads/new$', login_required(StartNewEventThreadCreateAPIView.as_view()), name='api-events-threads-new'),  # GET
    url(r'api/event/(?P<pk>[0-9]+)/delete$', login_required(DeleteEventAPIView.as_view()), name='api-events-delete'),  # DELETE
    url(r'api/event/(?P<pk>[0-9]+)/edit$', login_required(UpdateEventAPIView.as_view()), name='api-events-edit'),  # POST
    url(r'api/event/(?P<event>[0-9]+)/threads/(?P<pk>[0-9]+)/send$', login_required(SendMessageToEventThreadAPIView.as_view()), name='api-event-thread-message-send'),  # POST
    url(r'api/event/(?P<pk>[0-9]+)/participants$', login_required(ListParticipantsAPIView.as_view()), name='api-events-participants-list'),  # GET
    url(r'api/event/(?P<pk>[0-9]+)/invited$', login_required(ListInvitedAPIView.as_view()), name='api-events-invited-list'),  # GET
    url(r'api/event/(?P<pk>[0-9]+)/invite$', login_required(InviteUserAPIView.as_view()), name='api-events-invite-contact'),  # POST
    url(r'api/event/(?P<pk>[0-9]+)/participate$', login_required(ParticipateInEventAPIView.as_view()), name='api-events-participate'),  # GET
    url(r'api/event/(?P<pk>[0-9]+)/cancel$', login_required(CancelParticipationInEventAPIView.as_view()), name='api-events-cancel'),  # GET
    url(r'id/(?P<pk>[0-9]+)$', login_required(EventDetailView.as_view()), name="view-events-detail"),  # GET
    url(r'id/(?P<pk>[0-9]+)/edit$', login_required(UpdateEventFormView.as_view()), name="view-events-edit"),  # GET
    path('map/national', login_required(NationalEventSearchTemplateView.as_view()), name='view-events-national-search'),
    path('new', login_required(CreateNewEventFormView.as_view()), name='view-events-create'),
    path('mine', login_required(MyEventsTemplateView.as_view()), name='view-events-mine-list'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('reports/', include('apps.reports.urls')),
    path('profile/', include('apps.profiles.urls')),
    path('auth/', include('apps.usermgmt.urls')),
    path('notifications/', include('apps.notifications.urls')),
    path('social/', include('apps.social.urls')),
    path('events/', include('apps.events.urls')),
    path('forums/', include('apps.forums.urls')),
    path('file_exchange/', include('apps.filesharing.urls')),
    path('feedback/', include('apps.feedback.urls')),
    path('mgmt/', include('apps.mgmt.urls')),
    path('quotas/', include('apps.quotas.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^api/captcha/', include('rest_captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/events/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.gis.db import models

from apps.globalutils.models import ThankableMixin
from apps.profiles.models import UserProfile
from django_countries.fields import CountryField
from crum import get_current_user
import reverse_geocode
from datetime import datetime
from django.urls import reverse


class EventType(models.TextChoices):
    MUP = 'MUP', 'Meetup',
    CUP = 'CUP', 'Cleanup',
    DEM = 'DEM', 'Demonstration',
    TRN = 'TRN', 'Training/Workshop',
    PRS = 'PRS', 'Presentation'
    OTR = 'OTR', 'Other'


class Event(models.Model):
    datetime_start = models.DateTimeField(null=False, blank=False)
    datetime_end = models.DateTimeField(null=False, blank=False)
    title = models.CharField(null=False, blank=False, max_length=250)
    description = models.TextField(null=False, blank=False, max_length=5000)
    category = models.CharField(max_length=3, choices=EventType.choices)
    geom = models.PointField(srid=4326, geography=True, blank=True, null=True, verbose_name="Coordinates")
    address = models.CharField(null=True, blank=True, max_length=250)
    country = CountryField(blank=True, null=True)
    admin = models.ForeignKey(UserProfile, null=True, blank=True, on_delete=models.CASCADE, related_name="events_created")
    cohosts = models.ManyToManyField(UserProfile, related_name="events_cohosting", blank=True)
    participants = models.ManyToManyField(UserProfile, related_name="events_participating", blank=True)
    invited = models.ManyToManyField(UserProfile, related_name="events_invited", blank=True)
    public = models.BooleanField(default=True)
    online = models.BooleanField(default=False)
    online_address = models.URLField(null=True, blank=True)
    notifications = GenericRelation('notifications.Notification', related_query_name='event')  # added for automatic deletion through cascade

    def get_detail_url(self):
        return reverse('view-events-detail', args=(self.id,))

    def __str__(self):
        return '{}: {} on {} at {} in {}'.format(self.category, self.title, self.datetime_start, self.geom, self.country)

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        user_profile = user.profile
        self.admin = user_profile
        if not self.online:
            switch_coordinates = [(self.geom[1], self.geom[0])]
            rev_res = reverse_geocode.search(switch_coordinates)
            if rev_res:
                self.country = rev_res[0]['country_code']
        super(Event, self).save(*args, **kwargs)
        self.participants.add(user_profile)


class EventThread(models.Model):
    author = models.ForeignKey(UserProfile, null=True, blank=True, editable=False, on_delete=models.CASCADE, related_name="initiated_event_threads")
    event = models.ForeignKey(Event, blank=False, related_name="event_threads", on_delete=models.CASCADE)
    started_timestamp = models.DateTimeField(null=False, default=datetime.now, editable=False)
    last_post_datetime = models.DateTimeField(null=False, default=datetime.now, editable=False)

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        if is_new:
            self.author = get_current_user().profile
        super(EventThread, self).save(*args, **kwargs)


class EventThreadMessage(ThankableMixin):
    thread = models.ForeignKey(EventThread, null=False, blank=False, on_delete=models.CASCADE, related_name="messages")
    sent_timestamp = models.DateTimeField(null=False, default=datetime.now, editable=False)
    author = models.ForeignKey(UserProfile, editable=False, null=True, blank=True, on_delete=models.CASCADE, related_name="event_messages")
    content = models.TextField(max_length=5000, blank=False, null=False, default='')

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        if is_new:
            self.author = get_current_user().profile
            thread = self.thread
            thread.last_post_datetime = self.sent_timestamp
            thread.save()
        super(EventThreadMessage, self).save(*args, **kwargs)

apps/events/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Event
from apps.reports.widgets import MapBoxWidget
from django.db.models import Q
from apps.profiles.models import UserProfile
from apps.social.models import ConnectionRequest
from crum import get_current_user


class NewEventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(NewEventForm, self).__init__(*args, **kwargs)

        # queryset for choices should only consist of connections
        current_profile = get_current_user().profile
        accepted_filter = Q(accepted=True)
        initiated_filter = Q(initiator=current_profile)
        recipient_filter = Q(recipient=current_profile)
        initiated_connections = ConnectionRequest.objects.filter(accepted_filter & initiated_filter).values('recipient__id')
        received_connections = ConnectionRequest.objects.filter(accepted_filter & recipient_filter).values('initiator__id')
        initiated_connections_filter = Q(id__in=initiated_connections)
        received_connections_filter = Q(id__in=received_connections)
        self.fields['cohosts'].queryset = UserProfile.objects.filter(initiated_connections_filter | received_connections_filter)
        self.fields['invited'].queryset = UserProfile.objects.filter(initiated_connections_filter | received_connections_filter)

        self.helper = FormHelper(self)

        self.helper.layout.append(Submit('save', 'save'))

    class Meta:
        model = Event
        exclude = ['admin']
        widgets = {'geom': MapBoxWidget(),
                   'description': forms.Textarea(attrs={'placeholder': 'Description', 'rows': '5'}),
                   'address': forms.TextInput(attrs={'placeholder': 'Name of the place, address...'}),
                   'title': forms.TextInput(attrs={'placeholder': 'Title'}),
                   }

apps/events/templates/create_event.html
{% extends base_template_name %}
{% block content %}
{% load static %}
{% load countries %}
{% get_countries as countries %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
<script type="text/javascript" src="{% static 'js/mapbox-gl.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/mapbox-gl.css' %}"/>
<script src="{% static 'js/mapbox-gl-geocoder.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/mapbox-gl-geocoder.css' %}" type="text/css"/>
<script type="text/javascript" src="{% static 'js/choices.min.js' %}"></script>
<link rel="stylesheet" property="stylesheet" href="{% static 'css/choices.min.css' %}"/>
<script type="text/javascript" src="{% static 'js/map-functions.js' %}"></script>
<script type="text/javascript" src="{% static 'js/tempusdominus-bootstrap-4.min.js' %}"></script>
<link rel="stylesheet" property="stylesheet" href="{% static 'css/tempusdominus-bootstrap-4.min.css' %}"/>

<div class="row d-flex flex-row">
        <form class="flex-grow-1" method="post" name="new_report" id="id_form_new_report" action="#">
                <div class="col flex-grow-1" id="div_form_new_event">
                    {% csrf_token %}
                    <div class="row form-row my-2">
                        <div class="col-3 col-xl-2">
                            <strong>Title</strong>
                        </div>
                        <div class="col-9 col-xl-10">
                            {{ form.title }}
                        </div>
                    </div>
                    <div class="row form-row my-2">
                        <div class="col-3 col-xl-2">
                            <strong>Category</strong>
                        </div>
                        <div class="col-9 col-xl-10">
                            {{ form.category }}
                        </div>
                    </div>
                    <div class="row form-row my-2">
                        <div class="col-3 col-xl-2">
                            <strong>Privacy</strong>
                        </div>
                        <div class="col-9 col-xl-10">
                            {{ form.public }}
                        </div>
                    </div>
                    <div class="row form-row my-2">
                        <div class="col-3 col-xl-2">
                            <strong>Start &amp; end</strong>
                        </div>
                        <div class="col-4">
                            <div class="input-group date" id="startdatetimepicker" data-target-input="nearest">
                                {{ form.datetime_start | attr:"data-target:#startdatetimepicker" | add_class:"datetimepicker-input" }}
                                <div class="input-group-append" data-target="#startdatetimepicker" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            -
                        </div>
                        <div class="col-4">
                            <div class="input-group date" id="enddatetimepicker" data-target-input="nearest">
                                {{ form.datetime_end | attr:"data-target:#enddatetimepicker" | add_class:"datetimepicker-input" }}
                                <div class="input-group-append" data-target="#enddatetimepicker" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row form-row my-2">
                        <div class="col-3 col-xl-2">
                            <strong>Description</strong>
                        </div>
                        <div class="col-9 col-xl-10">
                            {{ form.description | add_class:"w-100" }}
                        </div>
                    </div>
                    <div class="row form-row my-2">
                        <div class="col-3 col-xl-2">
                            <strong>Invitee management</strong>
                        </div>
                        <div class="col-4">
                            {{ form.cohosts | as_crispy_field }}
                        </div>
                        <div class="col">
                        </div>
                        <div class="col-4">
                            {{ form.invited | as_crispy_field }}
                        </div>
                    </div>
                    <div class="row form-row my-2">
                        <div class="col-3 col-xl-2">
                            <strong>Online</strong>
                        </div>
                        <div class="col-9 col-xl-10">
                            {{ form.online }}
                        </div>
                    </div>
                    <div class="row form-row my-2 d-none" id="online_address_container">
                        <div class="col-3 col-xl-2">
                            <strong>Web address</strong>
                        </div>
                        <div class="col-9 col-xl-10">
                            {{ form.online_address | add_class:"w-75" }}
                        </div>
                    </div>
                    <div class="row form-row my-2" id="offline_address_container">
                        <div class="col-3 col-xl-2">
                            <strong>Location</strong>
                        </div>
                        <div class="col-9 col-xl-10">
                            <div class="row">
                                <div class="col">
                                    {{ form.address | add_class:"w-75" }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{ form.geom | as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row form-row my-4">
                        <div class="col text-center">
                            <button class="btn btn-primary">{{ mode_button }}</button>
                        </div>
                    </div>
                </div>
        </form>
</div>

<script type="text/javascript" src="{% static 'js/create_event_post.js' %}"></script>
{% endblock %}

apps/events/templates/event_detail.html
{% extends base_template_name %}
{% block content %}
{% load static %}
{% load countries %}
{% get_countries as countries %}
<script type="text/javascript" src="{% static 'js/mapbox-gl.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/mapbox-gl.css' %}"/>
<script src="{% static 'js/mapbox-gl-geocoder.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/mapbox-gl-geocoder.css' %}" type="text/css"/>
<script type="text/javascript" src="{% static 'js/handlebars.js' %}"></script>
<script type="text/javascript" src="{% static 'templates/compiled/comment_thread.js' %}"></script>
<script type="text/javascript" src="{% static 'templates/compiled/comment_post.js' %}"></script>
<script type="text/javascript" src="{% static 'templates/compiled/userpreview.js' %}"></script>
<script type="text/javascript" src="{% static 'js/map-functions.js' %}"></script>
<script type="text/javascript" src="{% static 'js/choices.min.js' %}"></script>
<link rel="stylesheet" property="stylesheet" href="{% static 'css/choices.min.css' %}"/>
<script type="text/javascript" src="{% static 'js/event_detail_pre.js' %}"></script>
<div class="row d-flex flex-row h-100">
    <div class="col d-flex flex-column h-100">

        <div class="row">
            <div class="col-7">
                <div class="row">
                    <div class="col">
                        <h2>{{ event.title }} <span class="badge badge-secondary">{{ event.get_category_display }}</span></h2>
                        <input type="hidden" value="{{ event.id }}" id="id_event_id">
                        <input type="hidden" value="{{ event.geom.x }}" id="id_event_geom_x">
                        <input type="hidden" value="{{ event.geom.y }}" id="id_event_geom_y">
                        <input type="hidden" value="{{ event.online }}" id="id_event_online">
                        <input type="hidden" value="{{ participating }}" id="id_participating">
                        <input type="hidden" value="{{ admin }}" id="id_admin">
                        <input type="hidden" value="{% static 'img/markers/map-marker-blue.png' %}" id="id_marker_url">
                        <input type="hidden" value="{{ ctids.EventThreadMessage }}" id="id_ctid_eventthreadmessage">
                    </div>
                    <div class="col-auto">
                        {% if not admin %}
                            {% if participating %}
                            <button class="btn btn-primary" data-toggle="modal" data-target="#cancelParticipationModal">Cancel participation</button>
                            {% else %}
                            <button class="btn btn-primary" data-toggle="modal" data-target="#participateModal">Participate</button>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <p><i class="fas fa-fw fa-clock"></i> {{ event.datetime_start }} - {{ event.datetime_end }}</p>
                    </div>
                    <div class="col-6">
                        <p><i class="fas fa-fw fa-map-marker-alt"></i> {% if event.online %}{{ event.online_address }}{% else %}{{ event.address }}{% endif %}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <p><strong>Organizer{% if event.cohosts.all %}s{% endif %}: </strong>{{ event.admin }}{% if event.cohosts.all %} {% for cohost in event.cohosts %} {{ cohost }}, {% endfor %} {% endif %}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <i>{{ event.description }}</i>
                    </div>
                </div>
                <div class="row py-4">
                    <div class="col" id="participationMgmt">
                        {% if admin %}
                        <i>You are the organizer of this event. You can <a href="#" data-toggle="modal" data-target="#deleteEventModal">delete it&nbsp;<i class="fas fa-fw fa-trash-alt"></i></a>, <a href="{% url 'view-events-edit' event.id%}">edit it <i class="fas fa-fw fa-external-link-alt"></i></a>, or <a href="#" data-toggle="modal" data-target="#inviteContactToEventModal">invite more people&nbsp;<i class="fas fa-user-plus"></i></a>.</i>
                        {% endif %}
                        {% if cohost %}
                        <i>You are a cohost of this event. You can <a href="{% url 'view-events-edit' event.id%}">edit it <i class="fas fa-fw fa-external-link-alt"></i></a> or <a href="#" data-toggle="modal" data-target="#inviteContactToEventModal">invite more people&nbsp;<i class="fas fa-user-plus"></i></a>.</i>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-5" id="map_outer_div_container">
                <div id='map' style='width: 100%; height: 300px;'></div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    {% if participating or admin %}
                  <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="conversations-tab" data-toggle="tab" href="#conversations" role="tab" aria-controls="conversations" aria-selected="true">Conversations</a>
                  </li>
                  <li class="nav-item" role="presentation">
                    <a class="nav-link" id="participants-tab" data-toggle="tab" href="#participants" role="tab" aria-controls="participants" aria-selected="false">Participants</a>
                  </li>
                    {% endif %}
                </ul>
            </div>
        </div>

        <div class="tab-content d-flex flex-grow-1 verticalscroll justify-content-center" id="myTabContent">
            {% if participating or admin %}
          <div class="tab-pane fade show active w-75" id="conversations" role="tabpanel" aria-labelledby="conversations-tab">
            <div class="row my-2 py-2">
              <div class="col">
                  <button class="btn btn-primary" data-toggle="modal" data-target="#startNewThreadModal">New conversation&nbsp;<i class="fas fa-fw fa-plus"></i></button>
              </div>
            </div>
            <div class="row py-2">
              <div class="col" id="id_thread_container">
              </div>
            </div>
          </div>
            {% endif %}
          <div class="tab-pane fade w-75" id="participants" role="tabpanel" aria-labelledby="participants-tab">
            <div class="row my-2 py-2">
              <div class="col">
                  <button class="btn btn-primary" data-toggle="modal" data-target="#inviteContactToEventModal">Invite contacts&nbsp;<i class="fas fa-fw fa-plus"></i></button>
              </div>
            </div>
            <div class="row">
                <div class="col">
                    <h3>Participating</h3>
                    <div class="row justify-content-center" id="id_participants_container"></div>
                    <hr/>
                    <h3>Invited</h3>
                    <div class="row justify-content-center" id="id_invited_container"></div>
                </div>
            </div>
          </div>
        </div>

    </div>
</div>

<!-- modals below -->
<div class="modal fade in" id="deleteEventModal" tabindex="-1" role="dialog" aria-labelledby="deleteEventModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteEventModalLabel">Delete this event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="row">
              <div class="col">
                  <p>Are you sure you want to delete this event?</p>
              </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No, take me back</button>
        <button id="id_btn_delete" type="button" class="btn btn-primary" data-dismiss="modal">Yes, delete</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade in" id="startNewThreadModal" tabindex="-1" role="dialog" aria-labelledby="startNewThreadModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="startNewThreadModalLabel">Start new conversation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form>
              <div class="form-row d-flex py-2">
                  <div class="col flex-fill d-flex">
                      <textarea class="d-flex flex-fill verticalscroll" id="id_post_textarea" rows="5" placeholder="Type your message here..."></textarea>
                  </div>
              </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Discard thread</button>
        <button type="button" class="btn btn-primary" id="id_btn_startThread" data-dismiss="modal">Start thread</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade in" id="inviteContactToEventModal" tabindex="-1" role="dialog" aria-labelledby="inviteContactToEventModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="inviteContactToEventModalLabel">Invite contact to event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form>
              <div class="form-row pt-2">
                  <div class="col">
                      <p>Choose recipients from your connections:</p>
                  </div>
              </div>
              <div class="form-row pb-2">
                  <div class="col">
                      <select class="form-control" name="choices-connections" id="choices-connections" multiple="multiple">
                      </select>
                  </div>
              </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Discard</button>
        <button type="button" id="id_btn_inviteContacts" class="btn btn-primary" data-dismiss="modal">Invite contacts to event</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade in" id="participateModal" tabindex="-1" role="dialog" aria-labelledby="participateModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="participateModalLabel">Participate in event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          Do you want to participate in this event?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No, cancel</button>
        <button type="button" id="id_btn_participate" class="btn btn-primary" data-dismiss="modal">Yes, participate</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade in" id="cancelParticipationModal" tabindex="-1" role="dialog" aria-labelledby="cancelParticipationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cancelParticipationModalLabel">Cancel participation in event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          Do you want to participate in this event?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button type="button" id="id_btn_cancelParticipation" class="btn btn-primary" data-dismiss="modal">Yes, cancel participation</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="{% static 'js/event_detail_post.js' %}"></script>
{% endblock %}

apps/events/templates/my_events.html
{% extends base_template_name %}
{% block content %}
{% load static %}
{% load countries %}
{% get_countries as countries %}
<script type="text/javascript" src="{% static 'js/mapbox-gl.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/mapbox-gl.css' %}"/>
<script src="{% static 'js/mapbox-gl-geocoder.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/mapbox-gl-geocoder.css' %}" type="text/css"/>
<script type="text/javascript" src="{% static 'js/choices.min.js' %}"></script>
<link rel="stylesheet" property="stylesheet" href="{% static 'css/choices.min.css' %}"/>
<script type="text/javascript" src="{% static 'js/handlebars.js' %}"></script>
<script type="text/javascript" src="{% static 'templates/compiled/eventpreview.js' %}"></script>
<script type="text/javascript" src="{% static 'js/map-functions.js' %}"></script>
<script type="text/javascript" src="{% static 'js/enums.js' %}"></script>
<script type="text/javascript" src="{% static 'js/my_events_pre.js' %}"></script>
<div class="d-flex col flex-column h-100 verticalscroll">
    <div class="row">
        <div class="col">
            <ul class="nav nav-tabs">
              <li class="nav-item">
                  <a id="id_tab_upcoming" class="nav-link active" href="#"><h4>Upcoming events</h4></a>
              </li>
              <li class="nav-item">
                  <a id="id_tab_past" class="nav-link" href="#"><h4>Past events</h4></a>
              </li>
            </ul>
        </div>
    </div>
    <div class="row" id="id_row_upcoming">
        <div class="col" id="events_container_upcoming">
        </div>
    </div>
    <div class="row d-none" id="id_row_past">
        <div class="col" id="events_container_past">
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static 'js/my_events_post.js' %}"></script>
{% endblock %}